[SMAGENT-5327] fix(driver): fix build on RHEL 8.9 kernels (#220)
On recent RHEL8 kernels (namely starting with 4.18.0-506.el8)
the kmod driver will fail to build with the following error:

```
  CC [M]  /code/sysdig-rw/main.o
/code/sysdig-rw/main.c: In function 'scap_init':
/code/sysdig-rw/main.c:2897:23: error: assignment to 'char * (*)(const struct device *, umode_t *)' {aka 'char * (*)(const struct device *, short unsigned int *)'} from incompatible pointer type 'char * (*)(struct device *, umode_t *)' {aka 'char * (*)(struct device *, short unsigned int *)'} [-Werror=incompatible-pointer-types]
 2897 |  g_ppm_class->devnode = ppm_devnode;
      |                       ^
cc1: some warnings being treated as errors
```

Notice how Red Hat backported that change from kernel 6.2
into what looks like 4.18 for RHEL8.9, a few months after
backporting it into 5.14 for RHEL9.3.

So add the corresponding check, making sure not to break
RHEL9.0-9.2 which DO NOT contain such change.